name: onboarding
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_lints: ^5.0.0
  cupertino_icons: ^1.0.2
  image_picker: ^1.1.2  #gallery phone
  universal_io: ^2.0.4 #platform specific stuff
  sliding_up_panel: ^2.0.0+1
  salomon_bottom_bar: ^3.3.1
  navigation_history_observer: ^1.1.1
  http_parser: ^4.0.0
  shared_preferences: ^2.0.15
  file_picker: ^8.1.4 #gallery web
  lottie: ^3.0.0
  provider: ^6.0.5
  animated_text_kit: ^4.2.2
  socket_io_client: ^3.0.2
  fluttertoast: ^8.0.8 
  image_downloader: ^0.30.0 
  syncfusion_flutter_pdfviewer: ^27.2.4
  flutter_pdfview: ^1.3.4
  path_provider: ^2.0.11
  url_launcher: ^6.1.7
  dart_rss: ^3.0.2  
  intl: ^0.19.0
  flutter_web_auth: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/animations/analysing.json
    - assets/animations/inspect.json
    - assets/animations/upload.json
    - assets/animations/loading.json
    - assets/animations/done.json
    - assets/animations/deadline.json
    - assets/animations/motivation.json
    - assets/pdf/pdf1.pdf